### PR TITLE
Rename voting component

### PR DESCRIPTION
**Pull request by daniel-salin**
Renamed previously titled Voting component, used to set voting options when creating a new session, to VotingOptions.

### CODE REVIEW

**Comment by makander** [comment]
Getting following error: 

./src/components/App.js
Module not found: Can't resolve '../pages/NewSessions' in '/usr/app/src/components'

**Comment by fredbellinder** [comment]
@makander, how do I recreate this Error?

**Comment by makander** [comment]
Throw away the project and set it up again.  Check out branch and try.

Skickat från min iPhone

**Comment by makander** [comment]
Redid the process again and it works just fine now. I think  I screwed something up earlier. sorry @daniel-salin and thanks to @fredbellinder for verifying.

**Pull request merged**
